### ISSUE TITLE
stencil-toolkit - Incompatible with current nx 

### ISSUE THREAD

**Issue by creadicted** [aiao-io/aiao#107]
Your library requires an `angular.json` file and a `tsconfig.json` file. The nx setup changed and is now using either an `angular.json` or a `workspace.json` file and the  `tsconfig.json` is now renamed to `tsconfig.base.json` 

Generating a library and selecting jest will result in an error: 
> `Expected libs/<library-name>/tsconfig.json to exist. Please create one.`

**Comment by Jimmysh** [comment]
@creadicted stencil you can use https://github.com/nxext/nx-extensions
